### ISSUE TITLE
update Url på bilka og føtex på Playstation 5 Standard

### ISSUE THREAD

**Issue by Wajiddat18c** [mhenrichsen/ps5-stock#12]
Føtex:
   Gamle: https://www.foetex.dk/produkter/sony-playstation-5/100532624/
   Nye: https://www.foetex.dk/produkter/sony-playstation-5-standard/100532624/

Blika:
   Gamle: https://www.bilka.dk/produkter/sony-playstation-5/100532624/
   Nye: https://www.bilka.dk/produkter/sony-playstation-5-standard/100532624/

**Comment by mhenrichsen** [comment]
Opdateret :)
